[build]
  base = "client"
  command = "cd /opt/build/repo/client && npm install --legacy-peer-deps && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
